# Generated by Django 3.2.11 on 2022-01-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='시·군·구'),
        ),
    ]
