# Generated by Django 3.2.11 on 2022-01-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascot', '0002_alter_character_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='region',
            field=models.CharField(choices=[('서울', 'Seoul'), ('부산', 'Busan'), ('대구', 'Daegu'), ('인천', 'Incheon'), ('광주', 'Gwangju'), ('대전', 'Daejeon'), ('울산', 'Ulsan'), ('세종', 'Sejong'), ('경기', 'Gyeonggi'), ('강원', 'Gangwon'), ('충북', 'Chungbuk'), ('충남', 'Chungnam'), ('전북', 'Jeonbuk'), ('전남', 'Jeonnam'), ('경북', 'Gyeongbuk'), ('경남', 'Gyeongnam'), ('제주', 'Jeju')], db_index=True, max_length=10, verbose_name='지역'),
        ),
    ]
