# Generated by Django 3.2.11 on 2022-01-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascot', '0003_alter_character_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, upload_to='mascot/character/%Y/%M/%d', verbose_name='사진'),
        ),
    ]
